name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install LLVM toolchain and other utilities
        run: sudo apt install -y llvm clang lld mtools nasm
      - name: Make for amd64
        run: make
      - name: Upload binaries
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Binaries
          path: bin
      - name: Upload objects
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Objects
          path: obj
